version: 2

sphinx:
  fail_on_warning: false

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# The Python requirements required to build docs
python:
   install:
   - requirements: requirements-docs.txt
   - method: pip
     path: .
   system_package: true
   
formats:
  - pdf
  - epub
